import 'package:flutter/material.dart';

/// Icône associée à chaque module, par son identifiant dans `content.json`.
/// Un module inconnu reçoit une icône générique.
IconData iconePourModule(String moduleId) {
  return switch (moduleId) {
    // Les fondamentaux
    'grandeurs' => Icons.bolt,
    'courant' => Icons.waves,
    'circuits' => Icons.account_tree,
    'symboles' => Icons.schema,
    'unites' => Icons.straighten,
    'energie' => Icons.electric_meter,
    'materiaux' => Icons.layers,
    'calculs_circuits' => Icons.calculate,
    'magnetisme' => Icons.explore,
    'condensateurs' => Icons.adjust,
    'electronique' => Icons.memory,
    // La maison
    'installation' => Icons.house,
    'cablage' => Icons.electrical_services,
    'eclairage' => Icons.lightbulb,
    'lire_tableau' => Icons.dashboard,
    'mesures' => Icons.speed,
    'chauffage' => Icons.thermostat,
    'locaux_risques' => Icons.pool,
    'parafoudre' => Icons.flash_on,
    'courants_faibles' => Icons.router,
    'eclairage_exterieur' => Icons.yard,
    'domotique' => Icons.wifi,
    'alarme' => Icons.videocam,
    // Sécurité de base
    'securite' => Icons.health_and_safety,
    'physiologie' => Icons.accessibility_new,
    'enfants' => Icons.child_care,
    'secours' => Icons.medical_services,
    'epi' => Icons.back_hand,
    'outillage' => Icons.hardware,
    'foudre' => Icons.thunderstorm,
    'atex' => Icons.warning,
    'cem_sante' => Icons.monitor_heart,
    // Habilitation électrique
    'habilitation' => Icons.verified_user,
    'voisinage' => Icons.social_distance,
    'b0_bs' => Icons.person,
    'br' => Icons.build_circle,
    'b1_b2' => Icons.groups,
    'bc' => Icons.lock,
    'arc_tst' => Icons.flare,
    'haute_tension' => Icons.dangerous,
    'regimes_neutre' => Icons.alt_route,
    // Mesurer, dépanner, rénover
    'depannage' => Icons.build,
    'mesures_avancees' => Icons.rule,
    'plaque_signaletique' => Icons.badge,
    'normes' => Icons.gavel,
    'renovation' => Icons.construction,
    'cabler_tableau' => Icons.handyman,
    'selectivite' => Icons.toggle_on,
    'oscilloscope' => Icons.show_chart,
    'maintenance_preventive' => Icons.engineering,
    'devis_documents' => Icons.description,
    // Moteurs, industrie et machines
    'moteurs' => Icons.settings,
    'triphase' => Icons.stacked_line_chart,
    'cos_phi' => Icons.pie_chart,
    'industrie' => Icons.precision_manufacturing,
    'schemas_industriels' => Icons.map,
    'variateurs' => Icons.tune,
    'servomoteurs' => Icons.smart_toy,
    'securite_machines' => Icons.pan_tool,
    'cem_perturbations' => Icons.sensors,
    'induction_industrie' => Icons.microwave,
    'soudure' => Icons.whatshot,
    // Énergies et réseaux
    'reseaux' => Icons.hub,
    'postes_htb' => Icons.power_input,
    'hvdc' => Icons.swap_horiz,
    'smart_grid' => Icons.device_hub,
    'nucleaire' => Icons.factory,
    'hydraulique' => Icons.water,
    'eolien' => Icons.wind_power,
    'photovoltaique' => Icons.solar_power,
    'autoconsommation' => Icons.battery_saver,
    'batteries' => Icons.battery_charging_full,
    'hydrogene' => Icons.science,
    'energies_diverses' => Icons.volcano,
    // Transports et mobilité
    'vehicule_electrique' => Icons.ev_station,
    'automobile' => Icons.directions_car,
    'mobilite_legere' => Icons.electric_bike,
    'ferroviaire' => Icons.train,
    'aeronautique' => Icons.flight,
    'camping_car_bateau' => Icons.directions_boat,
    // Tertiaire et bâtiments techniques
    'tertiaire_erp' => Icons.apartment,
    'ssi' => Icons.local_fire_department,
    'gtb' => Icons.domain,
    'ventilation' => Icons.air,
    'pac' => Icons.hvac,
    'secours_energie' => Icons.power,
    'eclairage_public' => Icons.light,
    'portails_ascenseurs' => Icons.elevator,
    'pompes_eau' => Icons.water_drop,
    'data_centers' => Icons.dns,
    'cuisines_pro' => Icons.restaurant,
    // Milieux spécialisés et vie du métier
    'agriculture' => Icons.agriculture,
    'medical' => Icons.local_hospital,
    'spectacle' => Icons.theater_comedy,
    'telecoms' => Icons.cell_tower,
    'electrochimie' => Icons.biotech,
    'factures_pro' => Icons.receipt_long,
    'recyclage' => Icons.recycling,
    'metiers' => Icons.work,
    'histoire' => Icons.history_edu,
    _ => Icons.menu_book,
  };
}
